### ISSUE TITLE
incomplete uninstallation

### ISSUE THREAD

**Issue by mohammadhakim73** [younes-mirinezhad/Scrips#1]
sometimes there need to be a "sudo apt-get autoremove" at the end to achieve a complete deletation

**Comment by younes-mirinezhad** [comment]
> sometimes there need to be a "sudo apt-get autoremove" at the end to achieve a complete deletation

Thank you, Mohammad  
CUDA_CUDNN uninstaller needs this code?  
I will check it as soon as possible.

**Comment by mohammadhakim73** [comment]
> 
Yes, after uninstalling CUDA_CUDNN with this script i faced a version conflict while installing again. Seem it could not delete completely, sudo apt-get autoremove will free up few more space and then installation can be done .

**Comment by younes-mirinezhad** [comment]
> > 
> 
> Yes, after uninstalling CUDA_CUDNN with this script i faced a version conflict while installing again. Seem it could not delete completely, sudo apt-get autoremove will free up few more space and then installation can be done .

I added this code. Thank you.
